# Web Deployment external variables

# WEB HOST DIRECTORIES (WINDOWS)
WEB_SOURCE_DIR: 'C:\Users\rhunt\test'
WEB_SITES_DIR: '{{ WEB_SOURCE_DIR }}\HOST'
WEB_ARCHIVE_DIR: '{{ WEB_SOURCE_DIR }}\HOST_ARCHIVE'


# WEB STATICS DIRECTORIES (LINUX)
STATIC_SOURCE_DIR: /home/rhunt/statics
STATICS_DIR: '{{ STATIC_SOURCE_DIR }}/content'
STATICS_ARCHIVE_DIR: '/tmp'


# NGINX DIRECTORIES (LINUX)
NGINX_SOURCE_DIR: /home/rhunt/nginx
NGINX_WEBSITES_DIR: '{{ NGINX_SOURCE_DIR}}/websites'
NGINX_MEDIA_SITE_DIR: '{{ NGINX_WEBSITES_DIR }}/media/site'

