# Web Deployment external variables

# --------------------------------------------------------
# WEB HOST DIRECTORIES (WINDOWS)
# -----------------------------------------------------
# Actual targets (when not testing):
# WEBSOURCE DIR:         C:\
# WEBSITES DIR:          C:\Websites
# WEBSITES ARCHIVE DIR:  D:\Websites
# --------------------------------------------------------
WEB_SOURCE_DIR: C:\Users\rhunt\test
WEB_WEBSITES_DIR: '{{ WEB_SOURCE_DIR }}\websites'
WEB_MEDIA_DIR: '{{ WEB_WEBSITES_DIR }}\media'
WEB_ARCHIVE_DIR: '{{ WEB_SOURCE_DIR }}\backup'

# --------------------------------------------------------
# WEB STATICS DIRECTORIES (LINUX)
# --------------------------------------------------------
# Actual targets (when not testing):
# STATICS SOURCE DIR:         /var/www
# STATICS WEBSITES DIR:       /var/www/websites
# STATICS WEBSITE MEDIA DIR:  /var/www/websites/media
# STATICS MEDIA SITE DIR:     /var/www/websites/media/site
# --------------------------------------------------------
STATICS_BASE_DIR: /home/rhunt/nginx
STATICS_WEBSITES_DIR: '{{ STATICS_BASE_DIR }}/websites'
STATICS_MEDIA_DIR: '{{ STATICS_WEBSITES_DIR }}/media'
STATICS_MEDIA_SITE_DIR: '{{ STATICS_MEDIA_DIR }}/site'
STATICS_ARCHIVE_DIR: '{{ STATICS_BASE_DIR }}/archive'
STATICS_CSS_FILE: my.css
STATICS_JS_FILE: my.js

# TESTING PURPOSES
STATICS_ARCHIVE_FILE: '{{ STATICS_BASE_DIR }}/archive.zip'

# --------------------------------------------------------
# LOCAL (ANSIBLE MASTER NODE) DIRECTORIES 
# --------------------------------------------------------
LOCAL_TMP: /tmp


# --------------------------------------------------------
# WINDOWS APACHE SERVICE NAMES
# --------------------------------------------------------
APACHE_SERVICES:
  - Apache2.2-2Zend
  - Apache2.4

# --------------------------------------------------------
# IMAGE FILE INFOMATION
# --------------------------------------------------------
MEDIA_ZIP_FILE: media.static.zip
