all:
  hosts:
    pcldevelastic01:
      ansible_host: 127.0.0.1
      ansible_port: 1222
      ansible_connection: local
      ansible_user: chunt

  children:
    ansible_test:
      hosts:
        pcldevapache:
          amsible_host: 172.19.100.61
          ansible_port: 12222
          ansible_connection: smart
          ansible_user: chunt
