all:
  hosts:

    pcldevelastic01:
      ansible_host: 127.0.0.1
      ansible_port: 1222
      ansible_user: rhunt
      ansible_connection: local

  children:
    development_servers:
      hosts:

        pcldevapache:
          ansible_host: PCLDEVAPACHE.DEVELOPMENT.PCLENDER.LOCAL
          ansible_port: 12222
          ansible_user: rhunt
          ansible_connection: smart

        pcldevweb05:
          ansible_host: PCLDEVWEB05.DEVELOPMENT.PCLENDER.LOCAL
#          HTTPS
#          ansible_port: 5986
#          HTTP
          ansible_port: 5985
          ansible_user: rhunt@DEVELOPMENT.PCLENDER.LOCAL
          ansible_connection: winrm
          ansible_winrm_transport: kerberos
          ansible_winrm_cert_validation: ignore
          anisble_become: false

        pcldevweb06:
          ansible_host: PCLDEVWEB06.DEVELOPMENT.PCLENDER.LOCAL
#          HTTPS
#          ansible_port: 5986
#          HTTP
          ansible_port: 5985
          ansible_user: rhunt@DEVELOPMENT.PCLENDER.LOCAL
          ansible_connection: winrm
          ansible_winrm_transport: kerberos
          ansible_winrm_cert_validation: ignore
          anisble_become: false
